package com.userrole.support;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Abstract base class for all QE integration / API tests.
 *
 * Decisions from QE_TEST_PLAN.md:
 * - One shared Spring context for all subclasses (except RateLimitApiTest which requires
 *   its own context via @DirtiesContext to isolate rate-limit bucket state).
 * - @SpringBootTest with MOCK web environment — MockMvc is the HTTP layer.
 * - @ActiveProfiles("test") activates application-test.properties.
 * - @AutoConfigureMockMvc wires MockMvc automatically.
 *
 * Shared helpers:
 * - createAdminUserAndGetToken(): creates a user, assigns ADMIN role, logs in, returns JWT.
 *   Uses a synthetic bootstrap JWT (generated by JwtTestHelper with userId=-1) for the
 *   initial ADMIN-guarded calls before a real admin user exists.
 * - createUserAndGetToken(): creates a regular user, logs in, returns JWT and userId.
 * - createUser(): creates a user as admin, returns user ID.
 *
 * All concrete test classes that extend this class must NOT add their own
 * @SpringBootTest or @AutoConfigureMockMvc annotations.
 */
@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
public abstract class BaseApiTest {

    @Autowired
    protected MockMvc mockMvc;

    @Autowired
    protected ObjectMapper objectMapper;

    @Autowired
    protected JwtTestHelper jwtTestHelper;

    // ====================================================================
    // Admin bootstrap helpers
    // ====================================================================

    /**
     * Creates an admin user in the DB, assigns the ADMIN role, logs in, and
     * returns the resulting JWT access token.
     *
     * This method is designed to be called at the start of tests that need an
     * admin actor. The bootstrap uses a synthetic JWT (signed with the correct key
     * but for a non-existent userId=-1) solely to satisfy the @PreAuthorize guard
     * while the first real admin user is being created.
     */
    protected String createAdminUserAndGetToken() throws Exception {
        return createAdminUserAndGetToken(TestDataFactory.createUserRequest("admin"));
    }

    protected String createAdminUserAndGetToken(com.userrole.user.dto.CreateUserRequest adminReq) throws Exception {
        // Step 1: Bootstrap token with userId=-1 to satisfy @PreAuthorize while creating the user.
        // This token is only used for POST /api/v1/users which does NOT record performed_by.
        String bootstrapCreate = jwtTestHelper.adminToken(-1L, "bootstrap");

        // Create the real admin user and get their real DB-persisted ID
        Long adminUserId = createUserWithToken(bootstrapCreate, adminReq);

        // Step 2: Now that the real admin user exists in the DB, build a token using their
        // actual userId so the audit log's FK constraint (performed_by -> users.id) is satisfied.
        String bootstrapAssign = jwtTestHelper.adminToken(adminUserId, adminReq.username());

        // Find the seeded ADMIN role ID
        Long adminRoleId = findAdminRoleId(bootstrapAssign);

        // Assign ADMIN role — performed_by will be adminUserId (valid FK)
        mockMvc.perform(post("/api/v1/users/" + adminUserId + "/roles/" + adminRoleId)
                        .header("Authorization", jwtTestHelper.bearerHeader(bootstrapAssign)))
                .andExpect(status().isNoContent());

        // Log in as the real admin to get a JWT that carries the ADMIN role in its claims
        return loginAndGetToken(adminReq.username(), "Password1!");
    }

    /**
     * Creates a non-admin user and returns their JWT.
     * @return array of [userId (Long), accessToken (String)]
     */
    protected Object[] createRegularUserAndGetToken(String adminToken) throws Exception {
        return createRegularUserAndGetToken(adminToken, TestDataFactory.uniqueCreateUserRequest());
    }

    protected Object[] createRegularUserAndGetToken(String adminToken,
            com.userrole.user.dto.CreateUserRequest userReq) throws Exception {
        Long userId = createUserWithToken(adminToken, userReq);
        String token = loginAndGetToken(userReq.username(), "Password1!");
        return new Object[]{userId, token};
    }

    /**
     * Creates a user using the given admin token and returns the new user's ID.
     */
    protected Long createUserWithToken(String adminToken,
            com.userrole.user.dto.CreateUserRequest req) throws Exception {
        String body = objectMapper.writeValueAsString(req);
        String response = mockMvc.perform(post("/api/v1/users")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(body)
                        .header("Authorization", jwtTestHelper.bearerHeader(adminToken)))
                .andExpect(status().isCreated())
                .andReturn().getResponse().getContentAsString();
        return objectMapper.readTree(response).path("data").path("id").asLong();
    }

    /**
     * Logs in as the given username/password and returns the access token string.
     */
    protected String loginAndGetToken(String username, String password) throws Exception {
        String loginBody = """
                {"username":"%s","password":"%s"}
                """.formatted(username, password);
        String response = mockMvc.perform(post("/api/v1/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(loginBody))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();
        return objectMapper.readTree(response).path("data").path("accessToken").asText();
    }

    /**
     * Finds the ID of the seeded ADMIN role by listing all roles.
     */
    protected Long findAdminRoleId(String adminToken) throws Exception {
        String response = mockMvc.perform(get("/api/v1/roles")
                        .header("Authorization", jwtTestHelper.bearerHeader(adminToken)))
                .andReturn().getResponse().getContentAsString();

        JsonNode roles = objectMapper.readTree(response).path("data");
        for (JsonNode role : roles) {
            if (com.userrole.common.RoleConstants.ADMIN.equals(role.path("name").asText())) {
                return role.path("id").asLong();
            }
        }
        throw new IllegalStateException("ADMIN role not found in DB — V6 migration may not have run");
    }

    /**
     * Convenience: assert an HTTP status code is NOT 401.
     */
    protected static org.hamcrest.Matcher<Integer> isNot(int statusCode) {
        return org.hamcrest.Matchers.not(statusCode);
    }
}
