-- V1: Create users table
-- Foundation table — no FK dependencies

CREATE TABLE users (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR(255)    NOT NULL,
    password_hash VARCHAR(255)    NOT NULL,
    full_name     VARCHAR(255)    NOT NULL,
    department    VARCHAR(255),
    email         VARCHAR(255)    NOT NULL,
    phone         VARCHAR(50),
    active        BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email UNIQUE (email)
);
