-- V2: Create roles and permissions tables
-- permissions.entity_type_id FK to entity_types is added in V3 (forward reference fix)

CREATE TABLE roles (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)    NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE permissions (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    role_id        BIGINT       NOT NULL,
    action         VARCHAR(50)  NOT NULL,
    entity_type_id BIGINT       NOT NULL,
    CONSTRAINT pk_permissions PRIMARY KEY (id),
    CONSTRAINT fk_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT uq_permissions_role_action_entity UNIQUE (role_id, action, entity_type_id)
);
