-- V3: Create entity_types and entity_instances tables
-- Also adds the forward-reference FK from permissions.entity_type_id to entity_types

CREATE TABLE entity_types (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)    NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_entity_types PRIMARY KEY (id),
    CONSTRAINT uq_entity_types_name UNIQUE (name)
);

CREATE TABLE entity_instances (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    entity_type_id BIGINT       NOT NULL,
    name           VARCHAR(255) NOT NULL,
    description    VARCHAR(1000),
    created_by     BIGINT       NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_entity_instances PRIMARY KEY (id),
    CONSTRAINT fk_entity_instances_entity_type FOREIGN KEY (entity_type_id) REFERENCES entity_types(id),
    CONSTRAINT fk_entity_instances_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Forward-reference FK: permissions.entity_type_id -> entity_types.id
-- This constraint was deferred to this migration because entity_types did not exist in V2
ALTER TABLE permissions
    ADD CONSTRAINT fk_permissions_entity_type FOREIGN KEY (entity_type_id) REFERENCES entity_types(id);
