-- V4: Create stored_tokens table for JWT refresh token persistence
-- FK on user_id -> users.id

CREATE TABLE stored_tokens (
    id            BIGINT          GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT          NOT NULL,
    refresh_token VARCHAR(2048)   NOT NULL,
    expires_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked       BOOLEAN         NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_stored_tokens PRIMARY KEY (id),
    CONSTRAINT fk_stored_tokens_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Index for efficient revocation queries when a user is soft-deleted
CREATE INDEX idx_stored_tokens_user_id ON stored_tokens(user_id);

-- Index for fast refresh token lookup
CREATE INDEX idx_stored_tokens_refresh_token ON stored_tokens(refresh_token);
