-- V5: Create user_roles join table and user_role_audit_log table
-- Depends on: users (V1), roles (V2)

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE user_role_audit_log (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT       NOT NULL,
    role_id      BIGINT       NOT NULL,
    role_name    VARCHAR(255) NOT NULL,
    action       VARCHAR(50)  NOT NULL,
    performed_by BIGINT       NOT NULL,
    performed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_user_role_audit_log PRIMARY KEY (id),
    CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_audit_log_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_audit_log_performed_by FOREIGN KEY (performed_by) REFERENCES users(id)
);

-- Index for efficient history queries per user
CREATE INDEX idx_user_role_audit_log_user_id ON user_role_audit_log(user_id);
