ALTER TABLE users ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE roles ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE entity_types ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE entity_types ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE entity_instances ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
